### ISSUE TITLE
enable_association internal server error

### ISSUE THREAD

**Issue by avipars** [Sniffleupagus/pwnagotchi_plugins#11]
https://github.com/Sniffleupagus/pwnagotchi_plugins/pull/6

**Comment by avipars** [comment]
you closed my issue without merging the pull request

**Comment by Sniffleupagus** [comment]
Yes. I didn't see the need for it.

**Comment by Sniffleupagus** [comment]
I made the error go away

**Comment by avipars** [comment]
thanks!
