### ISSUE TITLE
Missing - /etc/pwnagotchi/tweak_view.json

### ISSUE THREAD

**Issue by pull3t** [Sniffleupagus/pwnagotchi_plugins#13]
Hi,

Your tool is super useful! I've made a few pwnagotchi's and always get frustrated with the ui.

I am using tweak view, when I make changes via the webui the display will update. When I disable/enable the plugin the configuration reverts to default.  I get this error message:

Form

LIST bat.xy != '3,100', (135.0, 0)
Tweak VSS.bat.xy -> 3,100
LIST bat.xy != '3,100', (135.0, 0)
Tweak VSS.bat.xy -> 3,100
update from request err: UnboundLocalError("cannot access local variable 'ret' where it is not associated with a value")

I checked if /etc/pwnagotchi/tweak_view.json exists, the file is not there, I ran the commands:
sudo touch tweak_view.json
sudo chmod 666 tweak_view.json
-rw-rw-rw-  1 root root    0 Dec 16 11:02 tweak_view.json

File size did not change and the file is empty. Do you know what could be causing this? Thank you.

**Comment by pull3t** [comment]
I was able to trace the bug back to the update_form_requests function, the variable 'ret' is not initialised. Initalising at the start of the function resolved the error.

    def update_from_request(self, request):
        ret = " "
        res = "<ul>"
        changed = False

**Comment by Sniffleupagus** [comment]
Did that actually fix anything? I replace the stray "ret" with "res" that it should be. But it only gets to that code if it fails to open the file. Maybe it will report the actual error now.

**Comment by Sniffleupagus** [comment]
Try grabbing the new version and see why the file isn't getting created/modified

**Comment by pull3t** [comment]
Yes, adding ret = " " resolved the issue, I was able to adjust the position of elements, save and reboot and the configuration would be retained. 

I have tested your latest code and it works as expected. Thank you :)

**Comment by Sniffleupagus** [comment]
I believe this has been fixed
