### ISSUE TITLE
Forgot to comment line in miyagi.py

### ISSUE THREAD

**Issue by xentrify** [Sniffleupagus/pwnagotchi_plugins#4]
Line: https://github.com/Sniffleupagus/pwnagotchi_plugins/blob/79d52019a6a6b554f90344653808fa18d13362ef/miyagi.py#L226
Update that broke it: https://github.com/Sniffleupagus/pwnagotchi_plugins/commit/79d52019a6a6b554f90344653808fa18d13362ef

You forgot to comment that part or to get the right indent. When loaded, you get indent errors.

**Comment by Sniffleupagus** [comment]
That’ll teach me to edit remotely on the GitHub app without testing.

i just pushed another fix through the GitHub app, remotely, without testing. But that should fix it.

Thanks!

**Comment by xentrify** [comment]
Haha, I already thought that was the case. I Had no way to reach you because you don't have any social links and had to create an issue. It all works now. Thanks for creating the plugin! Hope that custom positioning will be added in the future.

**Comment by Sniffleupagus** [comment]
Yeah. I’ll do that when i am back in civilization and can test it. I use the tweakview plugin to reposition everything, so I didn’t think about putting it in the plugin.

**Comment by xentrify** [comment]
Take your time. Is it okay if I copy your miyagi plugin, modify it and publish it on my repo? I want to add some features that I find helpful. I can also make a pull request, but I've never done that before. Thanks alot!

**Comment by Sniffleupagus** [comment]
I don’t mind at all. Curious to see what you come up with.

**Comment by xentrify** [comment]
Thanks! I'll just add some QoL things I find useful. Publishing makes for easy download!

**Comment by xentrify** [comment]
I've released a version that allows custom positioning. I have some issues adding other features due to `on_ai_training_step` only being called once. Do you also experience this issue? On jayofelony's image v2.8.9.

**Comment by Sniffleupagus** [comment]
I know I’ve seen mine on “Tr27” and other numbers higher than 1, so it does get called. I’m not running jayofelony image, and have a different plugin event handler, and maybe other differences. I’m not able to easily check, but if you compare my pwnagotchi-snflpgs repo to his, there might be something. That is probably handled in ai/train.py or ai/__init__.py

**Comment by Sniffleupagus** [comment]
I just looked and can’t figure out what calls on_ai_training_step on ai/train.py.

**Comment by xentrify** [comment]
I had already figured out which script calls it (I will edit this when I get on my PC again). I know it worked for me on aluminum-ice’s image, but somehow not on jayofelony’s… I’ll ask him. Anyways, I named it miyagi_v2 as I use some of your plugins and I would otherwise have two miyagi plugins. I didn’t think better_miyagi would suit it as its really just some small personal changes.
